apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t3d8axzz2-java-quarkus
  janus-idp.io/tekton: t3d8axzz2-java-quarkus
  backstage.io/kubernetes-id: t3d8axzz2-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t3d8axzz2-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
